#!/bin/sh


if [ "$1" = "configure" ]; then

   if [ ! -f /etc/max-control/conf.inc.php ]; then
     cp /usr/share/max-control/conf.inc.php.example /etc/max-control/conf.inc.php
     chmod 640 /etc/max-control/conf.inc.php
     chown root:www-data /etc/max-control/conf.inc.php
     echo ""
     echo "WARNING: Edit /etc/max-control/conf.inc.php"
     echo ""
   fi

   chmod 775 /var/lib/max-control/cache
   chown -R www-data:www-data /var/lib/max-control/cache

   if grep -q ^www-data /etc/sudoers; then
     cat << EOF >> /etc/sudoers

# max-control www-data need to exec /usr/bin/max-control
www-data	ALL=NOPASSWD: /usr/bin/max-control


EOF
   fi

   # copy netlogon files
   if [ -d /home/samba/netlogon ] && [ ! -e /home/samba/netlogon/logon.bat ]; then
       cp /usr/share/max-control/netlogon/* /home/samba/netlogon/
       chown root:root /home/samba/netlogon/*
       chmod 644 /home/samba/netlogon/*
       unix2dos /home/samba/netlogon/logon.bat
       unix2dos /home/samba/netlogon/logon.kix
   fi


   [ -x /usr/sbin/a2enmod ] && a2enmod mod_rewrite

   if [ -x "/etc/init.d/apache2" ]; then
    if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
        invoke-rc.d apache2 reload || true
    else
        /etc/init.d/apache2 reload || true
    fi
  fi

fi
